Feature/separate dates2
ICESI-PI1-2024A-G1/proyecto-t1 pull request #48
Opened 2024-04-29 05:09 UTC by elkofix

Why: Separates the initial and final date

What: Gives a single column for the initial an other for the final date as the user requested

ToDo: Continue with another story

QA: unittest

2024-04-29 13:45 UTC, JMMA86 approved these changes
All is ok.

2024-04-29 13:48 UTC, ChrisBotina7823 approved these changes
hmmm

2024-04-29 13:51 UTC, ChrisBotina7823 requested changes
First solve the conflicts

2024-05-01 20:52 UTC, ChrisBotina7823 approved these changes

2024-05-02 02:55 UTC, merged